//! Tests for the synthetic generator.
//!
//! The important ones go through the *real* parser rather than re-reading the
//! bytes here: contract C1 §9.1's whole claim is that a generated file is
//! indistinguishable from a device recording, and a test that decoded the
//! file with the generator's own encoder would prove nothing about that.

use super::*;
use crate::parse;
use crate::session::Session;

/// Parses generated bytes, asserting the parse succeeded and was not
/// truncated.
fn parse_log(log: &[u8]) -> Session {
    let result = parse::parse(log).expect("generated bytes parse");
    assert!(result.truncation_warning.is_none(), "{:?}", result.truncation_warning);
    result.session
}

/// One channel's physical samples by registry name.
fn channel(session: &Session, name: &str) -> Vec<f64> {
    session
        .channels
        .iter()
        .find(|c| c.channel_id == name)
        .unwrap_or_else(|| panic!("no channel {name}"))
        .materialize()
}

fn small() -> SynthConfig {
    SynthConfig { laps: 2, lap_length_m: 120.0, imu_rate_hz: 25, ..SynthConfig::default() }
}

#[test]
fn generated_bytes_parse_as_a_schema_three_idl0_session() {
    // Arrange
    let config = small();

    // Act
    let out = generate(&config).unwrap();
    let session = parse_log(&out.log);

    // Assert
    assert_eq!(&out.log[0..4], b"IDL0");
    assert_eq!(out.log[4], 3);
    assert_eq!(session.session_id, out.truth.session.session_id);
    assert_eq!(session.device_id.as_deref(), Some(out.truth.session.device_id.as_str()));
    assert_eq!(session.timestamp_utc_ms, SESSION_START_UTC_MS);
}

#[test]
fn three_sensors_produce_all_eighteen_imu_channels_at_the_configured_rate() {
    // Arrange
    let config = small();

    // Act
    let session = parse_log(&generate(&config).unwrap().log);

    // Assert
    for index in 0..3 {
        for axis in ["AccelX", "AccelY", "AccelZ", "GyroX", "GyroY", "GyroZ"] {
            let name = format!("IMU{index}_{axis}");
            let ch = session
                .channels
                .iter()
                .find(|c| c.channel_id == name)
                .unwrap_or_else(|| panic!("no channel {name}"));
            assert_eq!(ch.nominal_rate_hz, config.imu_rate_hz as f64, "{name} rate");
            assert_eq!(ch.unit, if axis.starts_with("Accel") { "g" } else { "dps" }, "{name} unit");
        }
    }
}

#[test]
fn one_sensor_produces_only_that_sensors_channels() {
    // Arrange
    let config = SynthConfig { imu_count: 1, ..small() };

    // Act
    let session = parse_log(&generate(&config).unwrap().log);

    // Assert
    assert!(session.channels.iter().any(|c| c.channel_id == "IMU0_GyroZ"));
    assert!(!session.channels.iter().any(|c| c.channel_id.starts_with("IMU1_")));
    assert!(!session.channels.iter().any(|c| c.channel_id.starts_with("IMU2_")));
}

#[test]
fn imu_sample_count_matches_the_truth_on_every_axis() {
    // Arrange
    let config = small();

    // Act
    let out = generate(&config).unwrap();
    let session = parse_log(&out.log);

    // Assert
    let expected = out.truth.session.imu_sample_count;
    for index in 0..3 {
        for axis in ["AccelX", "GyroZ"] {
            let name = format!("IMU{index}_{axis}");
            assert_eq!(channel(&session, &name).len(), expected, "{name}");
        }
    }
}

#[test]
fn gps_fix_count_matches_the_truth() {
    // Arrange
    let config = small();

    // Act
    let out = generate(&config).unwrap();
    let session = parse_log(&out.log);

    // Assert
    assert_eq!(channel(&session, "GPS_SpeedKmh").len(), out.truth.session.gps_fix_count);
    assert_eq!(channel(&session, "GPS_Latitude").len(), out.truth.session.gps_fix_count);
}

#[test]
fn gps_positions_stay_inside_the_loops_own_bounding_box() {
    // Arrange
    let config = small();

    // Act
    let out = generate(&config).unwrap();
    let session = parse_log(&out.log);
    let lat = channel(&session, "GPS_Latitude");
    let lon = channel(&session, "GPS_Longitude");

    // Assert — the parser bakes lat/lon to decimal degrees at parse time
    // (ruling R27), so these are degrees already. Bounds are the semi-axes
    // the truth reports plus one 1e-7-degree storage step in metres.
    let lp = &out.truth.loop_;
    let margin = 1e-7 * lp.metres_per_deg_north;
    for (la, lo) in lat.iter().zip(lon.iter()) {
        let north_m = (la - lp.origin_lat_deg) * lp.metres_per_deg_north;
        let east_m = (lo - lp.origin_lon_deg) * lp.metres_per_deg_east;
        assert!(north_m.abs() <= lp.semi_minor_m + margin, "north {north_m}");
        assert!(east_m.abs() <= lp.semi_major_m + margin, "east {east_m}");
    }
}

#[test]
fn truth_laps_match_the_configured_count_and_tile_the_recording() {
    // Arrange
    let config = SynthConfig { laps: 4, ..small() };

    // Act
    let out = generate(&config).unwrap();

    // Assert
    assert_eq!(out.truth.laps.len(), 4);
    assert_eq!(out.truth.laps[0].start_s, 0.0);
    for pair in out.truth.laps.windows(2) {
        assert_eq!(pair[0].end_s, pair[1].start_s);
    }
    let last = out.truth.laps.last().unwrap();
    assert!((last.end_s - out.truth.session.duration_s).abs() < 1e-9);
    assert!(
        (out.truth.gps.total_distance_m - out.truth.loop_.perimeter_m * 4.0).abs() < 1e-9
    );
}

#[test]
fn lap_distance_is_the_requested_lap_length() {
    // Arrange
    let config = small();

    // Act
    let out = generate(&config).unwrap();

    // Assert
    for lap in &out.truth.laps {
        assert!((lap.distance_m - config.lap_length_m).abs() < 1e-6, "{}", lap.distance_m);
    }
}

#[test]
fn two_sensors_gyro_streams_differ_by_exactly_the_known_rotation() {
    // Arrange — noiseless, so the only residual is the i16 quantisation.
    let config = SynthConfig { noise_scale: 0.0, ..small() };
    let out = generate(&config).unwrap();
    let session = parse_log(&out.log);
    let rad_to_dps = 180.0 / PI;

    let s0: Vec<Vec3> = {
        let x = channel(&session, "IMU0_GyroX");
        let y = channel(&session, "IMU0_GyroY");
        let z = channel(&session, "IMU0_GyroZ");
        (0..x.len()).map(|i| [x[i], y[i], z[i]]).collect()
    };
    let s1: Vec<Vec3> = {
        let x = channel(&session, "IMU1_GyroX");
        let y = channel(&session, "IMU1_GyroY");
        let z = channel(&session, "IMU1_GyroZ");
        (0..x.len()).map(|i| [x[i], y[i], z[i]]).collect()
    };

    let rotation = out.truth.sensors[1].rotation_body_to_sensor;
    let bias0 = out.truth.sensors[0].gyro_bias_rad_s;
    let bias1 = out.truth.sensors[1].gyro_bias_rad_s;

    // Act / Assert — sensor 0 *is* the body frame (C1 §9.4), so removing its
    // bias recovers ω_body, and sensor 1 must be that rotated plus its own
    // bias. Tolerance is 0.15 dps: half an LSB is 0.031 dps, and the
    // rotation spreads sensor 0's three quantisation errors into each output
    // axis before sensor 1's own is added.
    for k in 0..s0.len() {
        let body = [
            s0[k][0] - bias0[0] * rad_to_dps,
            s0[k][1] - bias0[1] * rad_to_dps,
            s0[k][2] - bias0[2] * rad_to_dps,
        ];
        let predicted = mat_vec(&rotation, &body);
        for axis in 0..3 {
            let want = predicted[axis] + bias1[axis] * rad_to_dps;
            assert!(
                (s1[k][axis] - want).abs() < 0.15,
                "sample {k} axis {axis}: got {} want {want}",
                s1[k][axis]
            );
        }
    }
}

#[test]
fn a_stationary_upright_sensor_convention_holds_for_the_gravity_component() {
    // Arrange — the loop is planar and the imposed roll/pitch are small, so
    // every accelerometer's Z must sit near +1 g (SPEC §9's sign convention),
    // never near −1 g.
    let config = SynthConfig { noise_scale: 0.0, ..small() };

    // Act
    let session = parse_log(&generate(&config).unwrap().log);
    let az = channel(&session, "IMU0_AccelZ");

    // Assert
    let mean = az.iter().sum::<f64>() / az.len() as f64;
    assert!(mean > 0.8 && mean < 1.2, "mean accel_z {mean} g");
}

#[test]
fn the_same_seed_and_config_produce_byte_identical_logs() {
    // Arrange
    let config = small();

    // Act
    let first = generate(&config).unwrap();
    let second = generate(&config).unwrap();

    // Assert
    assert_eq!(first.log, second.log);
    assert_eq!(first.truth, second.truth);
}

#[test]
fn a_different_seed_produces_different_bytes_but_the_same_geometry() {
    // Arrange
    let a = small();
    let b = SynthConfig { seed: 2, ..small() };

    // Act
    let first = generate(&a).unwrap();
    let second = generate(&b).unwrap();

    // Assert
    assert_ne!(first.log, second.log);
    assert_eq!(first.truth.loop_, second.truth.loop_);
    assert_eq!(first.truth.laps, second.truth.laps);
    assert_ne!(first.truth.session.session_id, second.truth.session.session_id);
}

#[test]
fn noise_scale_zero_removes_the_run_to_run_difference_between_seeds() {
    // Arrange
    let a = SynthConfig { noise_scale: 0.0, seed: 1, ..small() };
    let b = SynthConfig { noise_scale: 0.0, seed: 2, ..small() };

    // Act
    let first = generate(&a).unwrap();
    let second = generate(&b).unwrap();

    // Assert — the seed still changes the session identity (it is part of
    // the hashed configuration), so only the record bytes are compared.
    let records = |log: &[u8]| log[wire::HEADER_PREFIX_LEN + 18 * wire::REGISTRY_ENTRY_LEN + 4..].to_vec();
    assert_eq!(records(&first.log), records(&second.log));
}

#[test]
fn more_noise_produces_more_spread() {
    // Arrange
    let quiet = SynthConfig { noise_scale: 0.0, ..small() };
    // The body's own gyro signal already has a ~14 dps spread, so "louder"
    // has to clear that, not just exceed zero.
    let loud = SynthConfig { noise_scale: 500.0, ..small() };

    let spread = |config: &SynthConfig| {
        let session = parse_log(&generate(config).unwrap().log);
        let xs = channel(&session, "IMU0_GyroX");
        let mean = xs.iter().sum::<f64>() / xs.len() as f64;
        (xs.iter().map(|x| (x - mean) * (x - mean)).sum::<f64>() / xs.len() as f64).sqrt()
    };

    // Act
    let (quiet_sd, loud_sd) = (spread(&quiet), spread(&loud));

    // Assert
    assert!(loud_sd > quiet_sd * 2.0, "quiet {quiet_sd} loud {loud_sd}");
}

#[test]
fn record_timestamps_never_go_backwards() {
    // Arrange
    let config = small();

    // Act
    let out = generate(&config).unwrap();
    let session = parse_log(&out.log);

    // Assert — the parser's own per-channel time vectors are strictly
    // increasing (C1 §3.5), which is only true if the file's record order was
    // non-decreasing to begin with.
    for ch in &session.channels {
        for pair in ch.t_us.windows(2) {
            assert!(pair[1] > pair[0], "{} went backwards", ch.channel_id);
        }
    }
}

#[test]
fn header_carries_the_configured_rates_and_mask() {
    // Arrange
    let config = SynthConfig { imu_count: 2, ..small() };

    // Act
    let log = generate(&config).unwrap().log;

    // Assert — SPEC §5.1 field offsets.
    let mask = u32::from_le_bytes(log[39..43].try_into().unwrap());
    assert_eq!(mask, 0xFFF);
    assert_eq!(log[43], 2);
    assert_eq!(u16::from_le_bytes(log[44..46].try_into().unwrap()), config.imu_rate_hz);
    assert_eq!(log[46], config.gps_rate_hz);
    assert_eq!(log[47], 12);
}

#[test]
fn a_configuration_out_of_range_is_a_typed_error() {
    // Arrange
    let cases = [
        (SynthConfig { laps: 0, ..small() }, SynthError::LapsOutOfRange(0)),
        (SynthConfig { lap_length_m: 1.0, ..small() }, SynthError::LapLengthOutOfRange(1.0)),
        (SynthConfig { imu_rate_hz: 0, ..small() }, SynthError::ImuRateOutOfRange(0)),
        (SynthConfig { gps_rate_hz: 0, ..small() }, SynthError::GpsRateOutOfRange(0)),
        (SynthConfig { imu_count: 4, ..small() }, SynthError::ImuCountOutOfRange(4)),
        (SynthConfig { noise_scale: -1.0, ..small() }, SynthError::NoiseOutOfRange(-1.0)),
    ];

    // Act / Assert
    for (config, want) in cases {
        assert_eq!(generate(&config).unwrap_err(), want);
    }
}

#[test]
fn rotation_angle_between_a_matrix_and_itself_is_zero() {
    // Arrange
    let r = rotation_zyx(0.3, -0.2, 0.1);

    // Act
    let angle = rotation_angle_between(&r, &r);

    // Assert — 1e-7, not tighter: near zero the identity goes through
    // `sqrt(1 − cos²θ)`, whose conditioning costs half the mantissa, so the
    // floor here is ~1.5e-8 radians (~1e-6 degrees) and no smaller.
    assert!(angle.abs() < 1e-7, "{angle}");
}

#[test]
fn rotation_angle_between_recovers_a_known_single_axis_rotation() {
    // Arrange — 20° of yaw apart.
    let a = rotation_zyx(0.0, 0.0, 0.0);
    let b = rotation_zyx(20.0 * PI / 180.0, 0.0, 0.0);

    // Act
    let angle = rotation_angle_between(&a, &b) * 180.0 / PI;

    // Assert
    assert!((angle - 20.0).abs() < 1e-9, "{angle}");
}

#[test]
fn the_committed_fixture_regenerates_byte_for_byte() {
    // Arrange
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/synth-3lap.idl0");
    let committed = std::fs::read(path).expect("committed fixture is present");

    // Act
    let out = generate(&SynthConfig::fixture()).unwrap();

    // Assert — a failure here is either an intentional generator change
    // (bump SYNTH_VERSION and re-commit, C1 §9.8) or a determinism bug.
    assert_eq!(out.log.len(), committed.len(), "fixture length changed");
    assert_eq!(out.log, committed, "fixture bytes changed");
}

#[test]
fn the_committed_fixture_truth_matches_the_regenerated_truth() {
    // Arrange
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/synth-3lap.truth.json");
    let committed = std::fs::read_to_string(path).expect("committed truth is present");

    // Act — compared as *text*, the way the CLI writes it, not as a
    // deserialised `Truth`: `serde_json`'s float parser can land one ULP off
    // the value its own writer emitted, so a struct comparison would fail on
    // a file that is byte-perfect. `.gitattributes` pins this file to LF so
    // the comparison holds on Windows too.
    let out = generate(&SynthConfig::fixture()).unwrap();
    let mut regenerated = serde_json::to_string_pretty(&out.truth).unwrap();
    regenerated.push('\n');

    // Assert
    assert_eq!(regenerated, committed);
}

#[test]
fn the_committed_fixture_stays_under_two_hundred_kilobytes() {
    // Arrange
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/synth-3lap.idl0");

    // Act
    let len = std::fs::metadata(path).expect("committed fixture is present").len();

    // Assert — C1 §9.8's budget, so the fixture stays committable.
    assert!(len <= 200 * 1024, "fixture is {len} bytes");
}

