//! Docs and agent group (C3 §3.10): `read_workbook_reference` and
//! `open_agent_terminal` (ruling R222 items 1–3).
//!
//! Both sit in §3.10 beside `get_settings`/`get_data_dir` for the same
//! reason those do: neither is a catalog row, an import, a workbook, a
//! tile, device I/O or sync. One reads a file bundled with the app; the
//! other starts a process in the user's own terminal.
//!
//! Same `_via`-suffixed idiom as `commands/app.rs`: each
//! `#[tauri::command]` resolves what only a running app can resolve (the
//! resource directory, the configured agent command) and delegates to a
//! plain function this module's own tests exercise directly.

use std::path::{Path, PathBuf};

use crate::error::{IpcError, IpcErrorKind};

/// The reference's file name inside the app's resource directory. Bundled
/// by `app/src-tauri/tauri.conf.json`'s `bundle.resources`, generated by
/// `idl-rs docs workbook` and kept honest by CI (ruling R222 item 1).
pub const WORKBOOK_REFERENCE_RESOURCE: &str = "WORKBOOK-REFERENCE.md";

/// C3 §3.10 `read_workbook_reference() -> string`.
///
/// Returns the bundled `WORKBOOK-REFERENCE.md` as Markdown, for the help
/// panel to render. Read from disk on every call rather than cached: the
/// panel opens on a keystroke, the file is tens of kilobytes, and a cache
/// would only matter if this were on the interaction path — it is not
/// (R201: `async`, off the main thread).
///
/// Errors: `not_found` (the resource is missing from the bundle — a
/// packaging fault, reported rather than papered over with an empty
/// document), `io`.
#[tauri::command(async)]
pub fn read_workbook_reference<R: tauri::Runtime>(app: tauri::AppHandle<R>) -> Result<String, IpcError> {
    use tauri::Manager;

    let path = app
        .path()
        .resolve(WORKBOOK_REFERENCE_RESOURCE, tauri::path::BaseDirectory::Resource)
        .map_err(|e| IpcError::new(IpcErrorKind::Io, format!("resolving the bundled reference: {e}")))?;
    read_workbook_reference_via(&path)
}

/// [`read_workbook_reference`]'s path-taking half.
fn read_workbook_reference_via(path: &Path) -> Result<String, IpcError> {
    if !path.is_file() {
        return Err(IpcError::new(
            IpcErrorKind::NotFound,
            format!("the workbook reference is not bundled with this build ({})", path.display()),
        ));
    }
    std::fs::read_to_string(path)
        .map_err(|e| IpcError::new(IpcErrorKind::Io, format!("reading {}: {e}", path.display())))
}

/// Writes `<data>/AGENTS.md` at launch (ruling R222 item 4), logging
/// rather than failing.
///
/// Lives here rather than in `app/src-tauri` so that crate stays thin
/// (CLAUDE.md §2) and keeps its single `idl-rs-tauri` dependency: the app
/// crate calls this one function and knows nothing about the template.
/// Never fatal — the library opens perfectly well without the file, and a
/// read-only or full disk must not stop the app starting.
pub fn ensure_agents_md_at_launch(data_root: &Path, app_version: &str) {
    match idl_rs::store::agents_md::ensure_agents_md(data_root, app_version) {
        Ok(idl_rs::store::agents_md::AgentsMdOutcome::Unchanged) => {}
        Ok(outcome) => eprintln!("AGENTS.md: {outcome:?}"),
        Err(e) => eprintln!("AGENTS.md unavailable: {e}"),
    }
}

/// C3 §3.10 `open_agent_terminal(context)`'s argument.
///
/// Both fields optional: the button exists in three places (the code
/// column, the Data tab's session detail, the status bar) and only the
/// first two have anything to say about what the user is looking at.
#[derive(Debug, Clone, Default, serde::Deserialize)]
pub struct AgentContextArg {
    /// The session the user is looking at, if any.
    pub session_id: Option<String>,
    /// The workbook the user is editing, if any — its file name or id, as
    /// the frontend knows it.
    pub workbook: Option<String>,
}

/// Builds the initial prompt the agent is started with (ruling R222 item
/// 3, whose wording this reproduces).
///
/// Pure, and the only place the prompt's text is written — the frontend
/// never composes it, so every entry point says the same thing.
pub fn agent_prompt(data_root: &Path, context: &AgentContextArg) -> String {
    let mut prompt = format!(
        "You are working in the idl1 library at {}. Read AGENTS.md first.",
        data_root.display()
    );
    let context_text = match (context.session_id.as_deref(), context.workbook.as_deref()) {
        (Some(session), Some(workbook)) => Some(format!("session {session}, workbook {workbook}")),
        (Some(session), None) => Some(format!("session {session}")),
        (None, Some(workbook)) => Some(format!("workbook {workbook}")),
        (None, None) => None,
    };
    if let Some(text) = context_text {
        prompt.push_str(&format!(" Context: {text}."));
    }
    prompt
}

/// Rejects a context field that could break out of the quoting the
/// platform's terminal invocation applies.
///
/// The prompt is built in Rust, but two of its substrings come from the
/// frontend, and two of the three platform paths below hand their command
/// line to a shell. Rather than write three correct quoters, the values
/// are constrained to what a session id and a workbook name actually are:
/// no quotes, no backslashes, no shell metacharacters, no control
/// characters, and nothing longer than a path component. A value outside
/// that is a bug in the caller, not a user's mistake, so it is
/// `invalid_argument` rather than a silently sanitised string.
fn check_context_field(label: &str, value: &str) -> Result<(), IpcError> {
    const FORBIDDEN: &[char] = &['"', '\'', '`', '\\', '$', '&', '|', ';', '<', '>', '(', ')', '{', '}', '\n', '\r'];
    if value.is_empty() || value.len() > 255 {
        return Err(IpcError::new(
            IpcErrorKind::InvalidArgument,
            format!("{label} must be between 1 and 255 characters"),
        ));
    }
    if value.chars().any(|c| FORBIDDEN.contains(&c) || c.is_control()) {
        return Err(IpcError::new(
            IpcErrorKind::InvalidArgument,
            format!("{label} contains a character that cannot appear in a terminal command"),
        ));
    }
    Ok(())
}

/// The same check over both optional fields.
fn check_context(context: &AgentContextArg) -> Result<(), IpcError> {
    if let Some(session_id) = context.session_id.as_deref() {
        check_context_field("session_id", session_id)?;
    }
    if let Some(workbook) = context.workbook.as_deref() {
        check_context_field("workbook", workbook)?;
    }
    Ok(())
}

/// The configured agent command, validated the same way.
///
/// A bare program name or an absolute path; never a shell line. The point
/// of the constraint is that the allowlist ruling R222 item 3 asks for is
/// meaningful: exactly one program is ever spawned, and it is the one the
/// user named in Settings.
fn check_agent_command(command: &str) -> Result<(), IpcError> {
    let trimmed = command.trim();
    if trimmed.is_empty() {
        return Err(IpcError::new(
            IpcErrorKind::InvalidArgument,
            "no agent command is configured (Settings ▸ Agent command)",
        ));
    }
    const FORBIDDEN: &[char] = &['"', '\'', '`', '$', '&', '|', ';', '<', '>', '\n', '\r'];
    if trimmed.chars().any(|c| FORBIDDEN.contains(&c) || c.is_control()) {
        return Err(IpcError::new(
            IpcErrorKind::InvalidArgument,
            "the configured agent command must be a program name or path, not a shell line",
        ));
    }
    Ok(())
}

/// `s` as a POSIX shell single-quoted word: wrapped in `'`, with every
/// embedded `'` closed, escaped and reopened (`'\''`).
///
/// Applied to *every* value spliced into a shell line, including the data
/// root — a library folder named `O'Brien` is ordinary, and an unquoted
/// path there would end the quoted string mid-command.
fn sh_single_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}

/// `s` as a PowerShell single-quoted string: wrapped in `'`, with every
/// embedded `'` doubled, which is PowerShell's own escape.
fn ps_single_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "''"))
}

/// `s` as the body of an AppleScript double-quoted string: `\` and `"`
/// escaped. The macOS path nests a shell line inside one of these, so the
/// shell quoting has to survive AppleScript's own parse first.
fn applescript_escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

/// One terminal invocation: the program to run and its arguments, with the
/// working directory applied by the caller.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TerminalInvocation {
    /// The program to spawn.
    pub program: String,
    /// Its arguments, already in order.
    pub args: Vec<String>,
}

/// Builds the platform's terminal invocation.
///
/// **Windows** (the supported platform): Windows Terminal when `wt.exe`
/// resolves — `wt.exe -d <cwd> <agent> <prompt>`, which starts the agent
/// in a new tab with no shell in between, so nothing in `prompt` is ever
/// interpreted. Otherwise `cmd /c start "" powershell -NoExit -Command
/// …`, which is the only way to get a *visible* console out of a GUI
/// process without Windows Terminal; that path does go through a shell,
/// which is why every value reaching it — the data root included — is
/// shell-quoted rather than spliced raw.
///
/// **macOS and Linux are untested** (ruling R222 item 3 says to document
/// them as such). The macOS path drives Terminal.app through `osascript`;
/// the Linux path calls `x-terminal-emulator`, the Debian alternatives
/// name, which is absent on distributions that do not use it. Neither has
/// been run on real hardware by this lane; both are written to be obvious
/// to fix rather than clever.
///
/// `wt_exe_present` is passed rather than probed so the decision is
/// testable on any machine.
pub fn terminal_invocation(
    os: &str,
    wt_exe_present: bool,
    cwd: &Path,
    agent_command: &str,
    prompt: &str,
) -> Result<TerminalInvocation, IpcError> {
    let cwd = cwd.display().to_string();
    match os {
        "windows" if wt_exe_present => Ok(TerminalInvocation {
            program: "wt.exe".to_string(),
            args: vec!["-d".to_string(), cwd, agent_command.to_string(), prompt.to_string()],
        }),
        "windows" => Ok(TerminalInvocation {
            program: "cmd".to_string(),
            args: vec![
                "/c".to_string(),
                "start".to_string(),
                String::new(),
                "powershell".to_string(),
                "-NoExit".to_string(),
                "-Command".to_string(),
                format!(
                    "Set-Location {}; & {} {}",
                    ps_single_quote(&cwd),
                    // `&` needs its program quoted too, or a path with a
                    // space is split into a program and its arguments.
                    ps_single_quote(agent_command),
                    ps_single_quote(prompt)
                ),
            ],
        }),
        "macos" => Ok(TerminalInvocation {
            program: "osascript".to_string(),
            args: vec![
                "-e".to_string(),
                format!(
                    "tell application \"Terminal\" to do script \"{}\"",
                    applescript_escape(&format!(
                        "cd {} && {} {}",
                        sh_single_quote(&cwd),
                        sh_single_quote(agent_command),
                        sh_single_quote(prompt)
                    ))
                ),
            ],
        }),
        "linux" => Ok(TerminalInvocation {
            program: "x-terminal-emulator".to_string(),
            args: vec![
                "-e".to_string(),
                "sh".to_string(),
                "-c".to_string(),
                format!(
                    "cd {} && {} {}",
                    sh_single_quote(&cwd),
                    sh_single_quote(agent_command),
                    sh_single_quote(prompt)
                ),
            ],
        }),
        other => Err(IpcError::new(
            IpcErrorKind::UnsupportedPlatform,
            format!("opening a terminal is not supported on {other}"),
        )),
    }
}

/// C3 §3.10 `open_agent_terminal(context)`.
///
/// Spawns the configured agent command in the user's terminal, with the
/// working directory set to `<data>` and an initial prompt built by
/// [`agent_prompt`]. Returns as soon as the terminal is started — it is
/// the user's process from then on, not the app's; nothing is piped back.
///
/// Desktop only: `unsupported_platform` on Android and iOS, where there is
/// no terminal to open.
///
/// Errors: `invalid_argument` (no agent command configured, or a context
/// value that cannot appear on a command line), `unsupported_platform`,
/// `io` (the terminal could not be started), `internal`.
#[cfg(not(any(target_os = "android", target_os = "ios")))]
#[tauri::command(async)]
pub fn open_agent_terminal<R: tauri::Runtime>(
    app: tauri::AppHandle<R>,
    data_dir: tauri::State<'_, crate::state::DataDir>,
    context: Option<AgentContextArg>,
) -> Result<(), IpcError> {
    use tauri::Manager;

    let config_dir = app
        .path()
        .app_config_dir()
        .map_err(|e| IpcError::new(IpcErrorKind::Io, format!("resolving the config directory: {e}")))?;
    let settings = idl_rs::store::settings::load(&config_dir.join("settings.json"));
    let context = context.unwrap_or_default();
    let invocation = plan_agent_terminal(&data_dir.0, &settings.agent_command, &context)?;

    // The shell plugin's **Rust** API, not its JS one: the webview is never
    // granted a shell permission at all (see `app/src-tauri/capabilities`),
    // so the allowlist ruling R222 item 3 asks for is exact — this call
    // site is the only way a process is ever spawned, and it spawns the one
    // program Settings names.
    use tauri_plugin_shell::ShellExt;
    app.shell()
        .command(&invocation.program)
        .args(&invocation.args)
        .current_dir(data_dir.0.clone())
        .spawn()
        .map_err(|e| {
            IpcError::new(IpcErrorKind::Io, format!("starting {}: {e}", invocation.program))
        })?;
    Ok(())
}

/// `open_agent_terminal` on mobile: there is no terminal to open.
#[cfg(any(target_os = "android", target_os = "ios"))]
#[tauri::command(async)]
pub fn open_agent_terminal<R: tauri::Runtime>(
    _app: tauri::AppHandle<R>,
    _data_dir: tauri::State<'_, crate::state::DataDir>,
    _context: Option<AgentContextArg>,
) -> Result<(), IpcError> {
    Err(IpcError::new(
        IpcErrorKind::UnsupportedPlatform,
        "opening an agent terminal is a desktop feature",
    ))
}

/// Everything [`open_agent_terminal`] decides before it touches a process:
/// validation, the prompt, and the platform invocation. Separated so the
/// whole decision is testable without a running app or a spawned terminal.
pub fn plan_agent_terminal(
    data_root: &Path,
    agent_command: &str,
    context: &AgentContextArg,
) -> Result<TerminalInvocation, IpcError> {
    check_agent_command(agent_command)?;
    check_context(context)?;
    let prompt = agent_prompt(data_root, context);
    terminal_invocation(
        std::env::consts::OS,
        wt_exe_present(),
        data_root,
        agent_command.trim(),
        &prompt,
    )
}

/// Whether `wt.exe` (Windows Terminal) resolves on this machine. Always
/// `false` off Windows, where the answer is not asked for.
fn wt_exe_present() -> bool {
    if std::env::consts::OS != "windows" {
        return false;
    }
    std::env::var_os("PATH")
        .map(|path| {
            std::env::split_paths(&path).any(|dir: PathBuf| dir.join("wt.exe").is_file())
        })
        .unwrap_or(false)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicU32, Ordering};

    fn temp_dir() -> PathBuf {
        static COUNTER: AtomicU32 = AtomicU32::new(0);
        let n = COUNTER.fetch_add(1, Ordering::Relaxed);
        let dir = std::env::temp_dir().join(format!("idl-rs-tauri-docs-{}-{n}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    fn ctx(session: Option<&str>, workbook: Option<&str>) -> AgentContextArg {
        AgentContextArg {
            session_id: session.map(str::to_string),
            workbook: workbook.map(str::to_string),
        }
    }

    #[test]
    fn read_workbook_reference_via_a_bundled_file_returns_its_text() {
        // Arrange
        let path = temp_dir().join("WORKBOOK-REFERENCE.md");
        std::fs::write(&path, b"# Workbook reference\n").unwrap();

        // Act
        let text = read_workbook_reference_via(&path).unwrap();

        // Assert
        assert_eq!(text, "# Workbook reference\n");
    }

    #[test]
    fn read_workbook_reference_via_a_missing_file_is_not_found() {
        // Arrange
        let path = temp_dir().join("absent.md");

        // Act
        let error = read_workbook_reference_via(&path).unwrap_err();

        // Assert — a packaging fault, reported rather than returned as an
        // empty document the help panel would render as a blank page.
        assert_eq!(error.kind, IpcErrorKind::NotFound);
    }

    #[test]
    fn agent_prompt_with_no_context_names_the_library_and_agents_md() {
        // Arrange
        let root = Path::new("/data");

        // Act
        let prompt = agent_prompt(root, &ctx(None, None));

        // Assert
        assert!(prompt.contains("You are working in the idl1 library at"));
        assert!(prompt.contains("Read AGENTS.md first."));
        assert!(!prompt.contains("Context:"));
    }

    #[test]
    fn agent_prompt_with_a_session_and_a_workbook_names_both() {
        // Arrange
        let root = Path::new("/data");

        // Act
        let prompt = agent_prompt(root, &ctx(Some("abc123"), Some("fork.idl1wb")));

        // Assert
        assert!(prompt.contains("Context: session abc123, workbook fork.idl1wb."));
    }

    #[test]
    fn plan_agent_terminal_with_an_empty_agent_command_is_invalid_argument() {
        // Arrange
        let root = temp_dir();

        // Act
        let error = plan_agent_terminal(&root, "   ", &ctx(None, None)).unwrap_err();

        // Assert
        assert_eq!(error.kind, IpcErrorKind::InvalidArgument);
    }

    #[test]
    fn plan_agent_terminal_with_a_shell_line_as_the_agent_command_is_invalid_argument() {
        // Arrange
        let root = temp_dir();

        // Act
        let error = plan_agent_terminal(&root, "claude; rm -rf /", &ctx(None, None)).unwrap_err();

        // Assert — exactly one program is ever spawned; a command that is
        // really a shell line is refused rather than quoted around.
        assert_eq!(error.kind, IpcErrorKind::InvalidArgument);
    }

    #[test]
    fn plan_agent_terminal_with_a_quote_in_the_session_id_is_invalid_argument() {
        // Arrange
        let root = temp_dir();

        // Act
        let error = plan_agent_terminal(&root, "claude", &ctx(Some("a' && whoami #"), None)).unwrap_err();

        // Assert
        assert_eq!(error.kind, IpcErrorKind::InvalidArgument);
    }

    #[test]
    fn terminal_invocation_on_windows_with_windows_terminal_runs_the_agent_with_no_shell() {
        // Arrange
        let cwd = Path::new("C:/data");

        // Act
        let invocation = terminal_invocation("windows", true, cwd, "claude", "hello").unwrap();

        // Assert
        assert_eq!(invocation.program, "wt.exe");
        assert_eq!(invocation.args, vec!["-d", "C:/data", "claude", "hello"]);
    }

    #[test]
    fn terminal_invocation_on_windows_without_windows_terminal_falls_back_to_powershell() {
        // Arrange
        let cwd = Path::new("C:/data");

        // Act
        let invocation = terminal_invocation("windows", false, cwd, "claude", "hello").unwrap();

        // Assert
        assert_eq!(invocation.program, "cmd");
        assert!(invocation.args.iter().any(|a| a == "powershell"));
        assert!(invocation.args.last().unwrap().contains("claude"));
    }

    #[test]
    fn terminal_invocation_on_an_unknown_platform_is_unsupported_platform() {
        // Arrange
        let cwd = Path::new("/data");

        // Act
        let error = terminal_invocation("plan9", false, cwd, "claude", "hello").unwrap_err();

        // Assert
        assert_eq!(error.kind, IpcErrorKind::UnsupportedPlatform);
    }

    #[test]
    fn terminal_invocation_on_every_supported_platform_carries_the_prompt() {
        // Arrange
        let cwd = Path::new("/data");

        // Act / Assert
        for os in ["windows", "macos", "linux"] {
            let invocation = terminal_invocation(os, false, cwd, "claude", "PROMPT").unwrap();
            assert!(
                invocation.args.iter().any(|a| a.contains("PROMPT")),
                "{os}: the prompt never reaches the agent"
            );
        }
    }

    #[test]
    fn terminal_invocation_a_data_root_containing_an_apostrophe_is_quoted_not_spliced() {
        // Arrange — `C:\Users\O'Brien\idl1` is an ordinary Windows library
        // path, and an unquoted one would close the shell string mid-command.
        let cwd = Path::new("C:/Users/O'Brien/idl1");

        // Act / Assert — PowerShell doubles the apostrophe; the two POSIX
        // shells close/escape/reopen it; and on macOS that escape's own
        // backslash is then doubled again for AppleScript, which strips one
        // before the shell ever sees the line.
        for (os, escaped) in [("windows", "O''Brien"), ("macos", "O'\\\\''Brien"), ("linux", "O'\\''Brien")] {
            let invocation = terminal_invocation(os, false, cwd, "claude", "hello").unwrap();
            let line = invocation.args.last().unwrap().clone();
            assert!(
                line.contains(escaped),
                "{os}: the apostrophe in the data root reached the shell unescaped: {line}"
            );
        }
    }

    #[test]
    fn terminal_invocation_an_agent_path_containing_a_space_stays_one_program() {
        // Arrange
        let cwd = Path::new("/data");

        // Act / Assert — an absolute path is a documented, supported value,
        // so it must not be split into a program and an argument.
        for os in ["windows", "macos", "linux"] {
            let invocation = terminal_invocation(os, false, cwd, "/Applications/My App/claude", "hello").unwrap();
            let line = invocation.args.last().unwrap().clone();
            assert!(
                line.contains("'/Applications/My App/claude'"),
                "{os}: the agent path was not quoted as one word: {line}"
            );
        }
    }

    #[test]
    fn sh_single_quote_a_value_with_an_apostrophe_closes_escapes_and_reopens() {
        // Arrange / Act
        let quoted = sh_single_quote("O'Brien");

        // Assert
        assert_eq!(quoted, "'O'\\''Brien'");
    }

    #[test]
    fn ps_single_quote_a_value_with_an_apostrophe_doubles_it() {
        // Arrange / Act
        let quoted = ps_single_quote("O'Brien");

        // Assert
        assert_eq!(quoted, "'O''Brien'");
    }

    #[test]
    fn applescript_escape_a_value_with_a_quote_and_a_backslash_escapes_both() {
        // Arrange / Act
        let escaped = applescript_escape(r#"a\b"c"#);

        // Assert
        assert_eq!(escaped, r#"a\\b\"c"#);
    }
}
