//! `<data>/AGENTS.md` — the orientation file an agent reads before it
//! touches the library (ruling R222 item 4).
//!
//! The app writes it on first launch and rewrites it when the app version
//! changes, so an agent opened in `<data>` by "Ask an agent" always finds a
//! file describing the layout it is actually looking at. The template lives
//! here, in core, because it documents C4's directory contract and the CLI's
//! verbs — both engine facts — not anything about the window it was
//! launched from.
//!
//! **Versioned, and rewritten wholesale.** The file opens with a
//! `<!-- idl1-agents-md: v<app version> -->` marker; [`ensure_agents_md`]
//! rewrites the file when that marker is absent or names a different
//! version, and leaves it alone otherwise. A user's own edits to it are
//! therefore not preserved across an app upgrade — deliberate, and stated
//! in the file's own first paragraph: this is generated orientation, and a
//! stale description of the folder layout is worse than a lost note.

use std::path::{Path, PathBuf};

/// The file's name at the data root.
pub const AGENTS_MD_FILENAME: &str = "AGENTS.md";

/// What [`ensure_agents_md`] did.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AgentsMdOutcome {
    /// The file did not exist and was written.
    Created,
    /// The file existed but carried a different (or no) version marker,
    /// and was rewritten.
    Rewritten,
    /// The file was already current; nothing was written.
    Unchanged,
}

/// Discriminant for [`AgentsMdError`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AgentsMdErrorKind {
    /// Reading or writing the file failed.
    Io,
}

/// Error from [`ensure_agents_md`]. Never `Err(String)` (CLAUDE.md §5).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AgentsMdError {
    /// Which class of failure.
    pub kind: AgentsMdErrorKind,
    /// Human-readable detail, including the path.
    pub message: String,
}

impl std::fmt::Display for AgentsMdError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{:?}: {}", self.kind, self.message)
    }
}
impl std::error::Error for AgentsMdError {}

/// The version marker line for `app_version`.
fn marker(app_version: &str) -> String {
    format!("<!-- idl1-agents-md: v{app_version} -->")
}

/// `<data>/AGENTS.md`'s path.
pub fn agents_md_path(data_root: &Path) -> PathBuf {
    data_root.join(AGENTS_MD_FILENAME)
}

/// Writes `<data>/AGENTS.md` if it is absent or was written by a different
/// app version; otherwise leaves it untouched.
///
/// `app_version` is the running app's version string (Tauri's
/// `package_info().version`), used only in the marker and the file's own
/// footer.
pub fn ensure_agents_md(data_root: &Path, app_version: &str) -> Result<AgentsMdOutcome, AgentsMdError> {
    let path = agents_md_path(data_root);
    let wanted = render_agents_md(app_version);

    let existing = std::fs::read_to_string(&path).ok();
    let outcome = match existing {
        None => AgentsMdOutcome::Created,
        Some(ref current) if current.starts_with(&marker(app_version)) => return Ok(AgentsMdOutcome::Unchanged),
        Some(_) => AgentsMdOutcome::Rewritten,
    };

    std::fs::create_dir_all(data_root)
        .and_then(|()| std::fs::write(&path, wanted.as_bytes()))
        .map_err(|e| AgentsMdError {
            kind: AgentsMdErrorKind::Io,
            message: format!("writing {}: {e}", path.display()),
        })?;
    Ok(outcome)
}

/// Renders the file's full text for `app_version`. Pure — exposed so the
/// CLI and the tests can render it without touching a disk.
pub fn render_agents_md(app_version: &str) -> String {
    format!(
        r#"{marker}
# AGENTS.md — the idl1 library

You are in an **idl1 data library**: the folder the idl1 app keeps every
recorded session, workbook and track in. This file is generated by the app
(version {app_version}) and is rewritten whenever the app is upgraded, so do
not keep notes in it.

## What is here

| Folder | What it holds | Treat it as |
|---|---|---|
| `blobs/` | Every imported log file, verbatim, named by its own SHA-256. | **Immutable.** Never edit, rename or delete a blob. |
| `sessions/` | One folder per session: `session.json` (C1 metadata) and `data.parquet`. | `data.parquet` is derived — a pure function of (blob, importer version). Never edit it; re-import instead. |
| `workbooks/` | `.idl1wb` files: Markdown with fenced `math`, `table`, `js` and prose cells. | **The truth, and the thing to edit.** A workbook is a file; the app is a live viewer of it. |
| `tracks/` | Track artifacts (circuit geometry, sectors). | Edit through the app. |
| `profiles/` | Bike profiles (`.idl0p`) — device configuration documents. | Edit through the app. |
| `derived/` | Content-addressed derived artifacts. | Disposable; regenerated on demand. |
| `catalog.sqlite` | The index over everything above. | **Disposable.** Delete it and `idl-rs library rebuild` reconstructs it. It is an index, never a source, and it is never synced. |
| `inbox/` | Drop a log file here and the app imports it. | A queue, not storage. |
| `tmp/` | Staging for atomic writes, and `tmp/quarantine/` for files that failed verification. | Do not write here yourself. |

## The rules that matter

1. **Log files and blobs are immutable.** If a recording is wrong, the fix
   is a new import or a workbook that corrects it, never an edited blob.
2. **Never edit `data.parquet`.** It is derived from a blob and an importer
   version. Editing it makes the library disagree with itself silently.
3. **The catalog is an index — deletable, rebuildable, never synced.** Do
   not read it as a source of truth and do not hand-edit it.
4. **Workbooks are the truth. Edit them.** They are plain Markdown; a text
   edit is a legitimate, first-class way to change one.
5. **Time is recorded, not assumed.** Every sample keeps its hardware
   timestamp; do not re-derive a time base.

## The CLI

The engine ships as `idl-rs`. Every structured command takes `--format json`
and answers with a JSON envelope; `--help` on any subcommand is authoritative.

```
idl-rs info <file.idl0>                     # session metadata: ids, start time, checksum
idl-rs channels <file.idl0>                 # every channel: rate, sample count, synthesized flag
idl-rs export <file.idl0> -o out.csv        # channels to CSV (long/tidy) or JSON
idl-rs import <file.idl0> --data <data>     # import a log into this library
idl-rs library scan --data <data>           # find log files not yet imported
idl-rs library fold-in <dir> --data <data>  # import a whole folder of logs
idl-rs library stale --data <data>          # sessions whose data.parquet predates the importer
idl-rs library rebuild --data <data>        # re-derive data.parquet for stale sessions
idl-rs library index --data <data>          # rebuild the lap/track index
idl-rs docs workbook --out REFERENCE.md     # regenerate the workbook reference
```

## Writing a workbook

The full language reference — every math builtin with its signature, unit
rule and shape, the definition annotations, the `js` cell's host variables,
and the chart grammar — is `docs/WORKBOOK-REFERENCE.md` in the idl1 source
repository, and is bundled into the app (Help ▸ Workbook reference, or `F1`
in the code editor). Read it before writing a `math` or `js` cell; the
function names follow scipy/numpy where the behaviour matches and
deliberately diverge where it does not, so guessing a name is unsafe.

---

*Generated by idl1 {app_version}. Rewritten on upgrade — keep your own notes elsewhere.*
"#,
        marker = marker(app_version),
        app_version = app_version
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use uuid::Uuid;

    fn temp_root() -> PathBuf {
        let dir = std::env::temp_dir().join(format!("idl-rs-agents-md-{}", Uuid::new_v4()));
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn ensure_agents_md_on_an_empty_root_creates_the_file() {
        // Arrange
        let root = temp_root();

        // Act
        let outcome = ensure_agents_md(&root, "0.1.0").unwrap();

        // Assert
        assert_eq!(outcome, AgentsMdOutcome::Created);
        assert!(agents_md_path(&root).is_file());
    }

    #[test]
    fn ensure_agents_md_run_twice_at_one_version_writes_once() {
        // Arrange
        let root = temp_root();
        ensure_agents_md(&root, "0.1.0").unwrap();

        // Act
        let outcome = ensure_agents_md(&root, "0.1.0").unwrap();

        // Assert
        assert_eq!(outcome, AgentsMdOutcome::Unchanged);
    }

    #[test]
    fn ensure_agents_md_after_a_version_change_rewrites_the_file() {
        // Arrange
        let root = temp_root();
        ensure_agents_md(&root, "0.1.0").unwrap();

        // Act
        let outcome = ensure_agents_md(&root, "0.2.0").unwrap();

        // Assert
        assert_eq!(outcome, AgentsMdOutcome::Rewritten);
        let text = std::fs::read_to_string(agents_md_path(&root)).unwrap();
        assert!(text.starts_with("<!-- idl1-agents-md: v0.2.0 -->"));
    }

    #[test]
    fn ensure_agents_md_over_a_file_with_no_marker_rewrites_it() {
        // Arrange
        let root = temp_root();
        std::fs::write(agents_md_path(&root), b"notes I kept here\n").unwrap();

        // Act
        let outcome = ensure_agents_md(&root, "0.1.0").unwrap();

        // Assert
        assert_eq!(outcome, AgentsMdOutcome::Rewritten);
    }

    #[test]
    fn render_agents_md_names_every_never_touch_rule() {
        // Arrange / Act
        let text = render_agents_md("0.1.0");

        // Assert — the four rules ruling R222 item 4 names by hand.
        assert!(text.contains("immutable"));
        assert!(text.contains("Never edit `data.parquet`"));
        assert!(text.contains("deletable, rebuildable, never synced"));
        assert!(text.contains("Workbooks are the truth"));
    }

    #[test]
    fn render_agents_md_gives_one_example_for_every_library_verb() {
        // Arrange / Act
        let text = render_agents_md("0.1.0");

        // Assert
        for verb in ["idl-rs import ", "library fold-in", "library scan", "library stale", "library rebuild", "library index"] {
            assert!(text.contains(verb), "{verb} has no example in AGENTS.md");
        }
    }

    #[test]
    fn render_agents_md_points_at_the_workbook_reference() {
        // Arrange / Act
        let text = render_agents_md("0.1.0");

        // Assert
        assert!(text.contains("docs/WORKBOOK-REFERENCE.md"));
    }
}
